# Site settings
title: Daniel Anderson
description: Personal portfolio showcasing projects and experience
baseurl: "/portfolio" # The subpath of your site, e.g. /portfolio
url: "https://dtand.github.io" # Your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima

# Collections
collections:
  pages:
    output: true
    permalink: /:name

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
